config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1:
      branch: main
      repo: https://github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-periwinkle-urchin.sh
        container: qc.acc_shaky-cinnabar-dolphin
  QC.Doc:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-gamboge-cassowary.sh
        container: qc.doc_scaly-taupe-catfish
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-sepia-dane.sh
        container: qc.doc_freaky-taupe-bee
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-magenta-buzzard.sh
        container: qc.doc_shaky-champagne-lionfish
  QC.Lic:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cinnabar-mongrel.sh
        container: qc.lic_sleazy-ochre-macaw
  QC.Sec:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-azure-tzu.sh
        container: qc.sec_gamy-amber-swan
  QC.Sty:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-auburn-beagle.sh
        container: qc.sty_cozy-brass-serval
  QC.Uni:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-tomato-whale.sh
        container: qc.uni_surly-bistre-serval
  QC.Ver:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-razzmatazz-flamingo.sh
        container: qc.ver_hazy-grey-cockroach
timeout: 5400
