config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1:
      branch: main
      repo: https://github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-brass-hound.sh
        container: qc.acc_squeaky-wheat-loon
  QC.Doc:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-seashell-spider.sh
        container: qc.doc_muggy-salmon-wolverine
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-brown-starfish.sh
        container: qc.doc_gloppy-chartreuse-zebra
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-cobalt-bullfrog.sh
        container: qc.doc_geeky-russet-birman
  QC.Lic:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-chartreuse-frise.sh
        container: qc.lic_cranky-turquoise-harrier
  QC.Sec:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-white-mole.sh
        container: qc.sec_woozy-ultramarine-peccary
  QC.Sty:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-aquamarine-kangaroo.sh
        container: qc.sty_crabby-white-mongoose
  QC.Uni:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-flax-birman.sh
        container: qc.uni_boozy-cardinal-shrimp
  QC.Ver:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-emerald-javanese.sh
        container: qc.ver_crabby-goldenrod-crane
timeout: 5400
